export const portfolioConfig = {
  name: 'Murilo Alves',
  role: 'Desenvolvedor Front-end',
  location: 'Brasil',
  email: 'muriloa.pro@gmail.com',
  githubUsername: (import.meta.env.VITE_GITHUB_USERNAME || 'ItsMuriloa').trim(),
  githubUrl: 'https://github.com/ItsMuriloa/',
  linkedinUrl: 'https://www.linkedin.com/in/itsmuriloa/',
  eyebrow: 'Portfolio pessoal / Developer Lab',
  headline: 'Construindo ideias com código, automação e tecnologia.',
  bio:
    'Desenvolvedor em evolução, explorando web, IA, infraestrutura, servidores e soluções criativas para transformar curiosidade em projetos reais.',
  skills: [
    'Desenvolvimento Web',
    'Automações',
    'DevOps',
    'IA Generativa',
    'Git e GitHub',
    'APIs',
    'TypeScript',
    'PHP',
    'Python',
    'React',
    'Vite',
    'N8N',
  ],
  contactTitle: 'Tem uma ideia, projeto ou desafio técnico?',
  contactText: 'Bora conversar e transformar isso em algo funcional.',
  contactSubject: 'Contato pelo portfolio',
  contactBody: 'Olá Murilo, vi seu portfolio e gostaria de conversar sobre um projeto.',
};
