export const portfolioConfig = {
  name: 'Murilo Alves',
  role: 'Full Stack Developer',
  location: 'Brasil',
  email: 'muriloa.pro@gmail.com',
  githubUsername: (import.meta.env.VITE_GITHUB_USERNAME || 'ItsMuriloa').trim(),
  githubUrl: 'https://github.com/ItsMuriloa/',
  linkedinUrl: 'https://www.linkedin.com/in/itsmuriloa/',
  eyebrow: 'Portfolio pessoal / Backend-minded developer',
  headline: 'Construo sistemas, APIs e automações que resolvem problemas reais.',
  bio:
    'Desenvolvedor em evolução com foco em lógica, PHP, Laravel, MySQL, resolução de bugs e sistemas web organizados.',
  skills: [
    'PHP',
    'Laravel',
    'MySQL',
    'APIs',
    'JavaScript',
    'TypeScript',
    'React',
    'Tailwind CSS',
    'Docker',
    'Git e GitHub',
    'Automações',
  ],
  contactTitle: 'Tem uma ideia, projeto ou desafio técnico?',
  contactText: 'Vamos conversar e transformar isso em algo funcional.',
  contactSubject: 'Contato pelo portfolio',
  contactBody: 'Olá Murilo, vi seu portfolio e gostaria de conversar sobre um projeto.',
};
